sudo: false
language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev

matrix:
  allow_failures:
    - python: 3.5
    - python: "3.7-dev"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest tests/
